

services:
  mysql:
    image: mysql:latest
    container_name: meu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
