
services:
  db:
    image: mysql:latest
    container_name: meu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server1
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my_network
    environment:
      DATABASE_URL: mysql://root:root@db:3306/mydb
    volumes:
      - .:/app
    command: sh -c "npm run migrate && npm start"

networks:
  my_network:
